export enum ROUTES {
  POSTINGS = 'POSTINGS',
  WRITE_OFF = 'WRITE_OFF',
  AGENTS = 'AGENTS',
  INVENTORY = 'INVENTORY',
  POSTING_DETAIL = 'POSTING_DETAIL',
  AGENT_DETAIL = 'AGENT_DETAIL',
  WRITE_OFF_DETAIL = 'WRITE_OFF_DETAIL',
  INVENTORY_DETAIL = 'INVENTORY_DETAIL',
}
